import type { SellFormData } from '../../types/home';

export const initialFormData: SellFormData = {
  title: '',
  category: '',
  description: '',
  basicDetails: {
    year: '',
    make: '',
    model: '',
    manufacturer: '',
    engineHours: '',
    mileage: '',
  },
  general: {
    grossPower: '',
    operatingWeight: '',
    tireTrackSize: '',
    suspension: '',
    transmission: '',
    engineType: '',
    fuelType: '',
    cabType: '',
    tireTrackWear: '',
  },
  condition: {
    overallCondition: '',
    exteriorColor: '',
    interiorColor: '',
    batteriesHoldCharge: '',
    jumpStartRequired: '',
    parkingBrakeWorks: '',
  },
  engineCondition: {
    overAllCondition: '',
    oilLevelOk: '',
    anyLeaks: '',
    coolantLevel: '',
    smokeColor: '',
    engineNoise: '',
    coldStartQuality: '',
    checkEngineLight: '',
  },
  hydraulics: {
    hydraulicPumpCondition: '',
    cylinderLeaks: '',
    hoseCondition: '',
    hydraulicResponse: '',
    hydraulicsDamage: '',
  },
  cabElectronics: {
    dashboardFunctional: '',
    acHeaterWorking: '',
    displayErrors: '',
    seatCondition: '',
    controlsWorking: '',
    lightsWorking: '',
    sensorsWorking: '',
  },
  checkList: {
    exterior: {
      bodyPanels: '',
      bodyPanelsImages: [],
      glassMirrors: '',
      glassMirrorsImages: [],
      lightsSignals: '',
      lightsSignalsImages: [],
    },
    engine: {
      engineBlock: '',
      engineBlockImages: [],
      transmission: '',
      transmissionImages: [],
    },
    hydraulics: {
      hydraulicPump: '',
      hydraulicPumpImages: [],
      cylinders: '',
      cylindersImages: [],
    },
    underCarriage: {
      tracksWheels: '',
      tracksWheelsImages: [],
      suspension: '',
      suspensionImages: [],
    },
    functionalTest: {
      engineStart: '',
      engineStartImages: [],
      operationTest: '',
      operationTestImages: [],
    },
  },
  media: {
    exteriorImages: [],
    engineCompartMentImages: [],
    underCarriageTracksImages: [],
    cabInteiorImages: [],
    otherAttachments: [],
    videos: [],
  },
  additionalInformation: {
    equipmentIdentity: {
      vinNumber: '',
      manufacturerDate: '',
      modelYearConfirmation: '',
      equipmentHasDamage: '',
      maintainenceRecords: '',
      warrantyAvailable: '',
    },
    location: {
      address: '',
    },
    ownership: {
      ownershipProof: [],
      invoiceBillOfSale: [],
      governmentRegistration: [],
      emissionTest: [],
      insurance: [],
      maintenanceLog: [],
    },
  },
};

export const dropdownOptions = {
  transmission: [
    { id: 1, value: 'Automatic' },
    { id: 2, value: 'Manual' },
    { id: 3, value: 'Hydrostatic' },
  ],
  engineType: [
    { id: 1, value: 'Diesel' },
    { id: 2, value: 'Gasoline' },
    { id: 3, value: 'Electric' },
    { id: 4, value: 'Hybrid' },
  ],
  fuelType: [
    { id: 1, value: 'Diesel' },
    { id: 2, value: 'Gasoline' },
    { id: 3, value: 'Propane' },
  ],
  cabType: [
    { id: 1, value: 'Enclosed' },
    { id: 2, value: 'Open' },
    { id: 3, value: 'ROPS' },
  ],
  suspension: [
    { id: 1, value: 'track' },
    { id: 2, value: 'wheel' },
    { id: 3, value: 'combined' },
  ],
  overAllCondition: [
    { id: 1, value: 'Excellent' },
    { id: 2, value: 'Good' },
    { id: 3, value: 'Fair' },
    { id: 4, value: 'Poor' },
  ],
  exteriorColor: [
    { id: 1, value: 'red' },
    { id: 2, value: 'black' },
    { id: 3, value: 'other' },
  ],
  yesNo: [
    { id: 1, value: 'yes' },
    { id: 2, value: 'no' },
  ],
  coldStartQuality: [
    { id: 1, value: 'start easily' },
    { id: 2, value: 'normal' },
    { id: 3, value: 'difficult' },
    { id: 4, value: "won't start" },
  ],
  engineNoise: [
    { id: 1, value: 'Quiet' },
    { id: 2, value: 'Normal' },
    { id: 3, value: 'Loud' },
    { id: 4, value: 'Very Loud' },
  ],
};
